{
 "title": "Industrial_Defect_Detection_Safety",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Impeller Feed",
   "type": "text",
   "description": "Impeller Feed\n",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe src=\"http://localhost:8888/defectdetection.inference\" style=\"width:100%;height:100%;\"></iframe>"
   }
  },
  {
   "title": "Total Impellers Processed",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"impeller_defects\" and r[\"_field\"] == \"status\")\n  |> group()\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Control Room Entry Way Feed",
   "type": "text",
   "description": "Impeller Feed\n",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 0 },
   "options": {
    "content": "<iframe src=\"http://localhost:8888/industrialsafety.inference\" style=\"width:100%;height:100%;\"></iframe>"
   }
  },
  {
   "title": "#Defective Impellers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"impeller_defects\" and r[\"_field\"] == \"status\" and r[\"_value\"] == 0)\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "#OK Impellers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"impeller_defects\" and r[\"_field\"] == \"status\" and r[\"_value\"] == 1)\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  }
 ]
}