{
 "title": "Safety Dashboard - Linux",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Industrial Safety",
   "type": "text",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "<html>\n  <head>\n    <title>Industrial Safety</title>\n  </head>\n  <body>\n    <img src=\"http://localhost:5000/industrialsafety\" style=\"align:center;text-align:center;display:block;width:100%;height:100%\">\n  </body>\n</html>"
   },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"impeller_defects\" and r[\"_field\"] == \"status\" and r[\"_value\"] == 1)\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "People Detected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"industrial-safety-stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"person_count\")\n  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Safety Violations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Industrial_Detection_Safety\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"industrial-safety-stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"violations\")\n  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Target Hardware",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telegraf/industrial-safety-stream",
     "filter": { "fields": [ "target" ] }
    }
   ]
  },
  {
   "title": "Person Detection Model FPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telegraf/safety_fps", "filter": { "fields": [ "fps" ] } }
   ]
  }
 ]
}