@ECHO OFF 

ECHO Setting up Grafana...
copy defaults.ini "C:\Program Files\GrafanaLabs\grafana\conf\"
cd "C:\Program Files\GrafanaLabs\grafana\bin"
grafana-cli.exe plugins install agenty-flowcharting-panel
ECHO Grafana plugins installed successfully...
ECHO Setting up Grafana data sources...
copy ".\influx_datasource.yml" "C:\Program Files\GrafanaLabs\grafana\conf\provisioning\datasources\"
ECHO Setting up Grafana dashboards...
copy ".\defect_dashboard_windows.json" "C:\Program Files\GrafanaLabs\grafana\conf\provisioning\dashboards\"
copy ".\safety_dashboard_windows.json" "C:\Program Files\GrafanaLabs\grafana\conf\provisioning\dashboards\"
ECHO Restarting Grafana...
powershell -command "Restart-Service Grafana"
cd /D "%~dp0"
